kind: pipeline
name: default

workspace:
  base: /app
  path: git/drone

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

- name: test
  commands:
  - vendor/bin/phpunit --configuration phpunit.xml

trigger:
  branch:
  - master
  event:
  - push