kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/phpunit --configuration config.xml

trigger:
  branch:
  - master
  event:
  - push