<?php

namespace App\Constants;

/**
 * Class BlockId
 * 定义大区id
 *
 */
final class BlockID extends BasicEnum
{

    CONST BLOCK_TYPE_NORMAL_RED = 10010;
    CONST BLOCK_TYPE_NORMAL_YELLOW = 10011;
    CONST BLOCK_TYPE_NORMAL_BLUE = 10012;
    CONST BLOCK_TYPE_NORMAL_WHITE = 10013;
    CONST BLOCK_TYPE_NORMAL_BLACK = 10014;
    CONST BLOCK_TYPE_NORMAL_PINK = 10015;

    CONST PIG_NORMAL = 10050;

}